-- 코드를 입력하세요
SELECT U.USER_ID, U.NICKNAME, U.CITY || ' ' || U.STREET_ADDRESS1 || ' ' || U.STREET_ADDRESS2 AS 전체주소, SUBSTR(U.TLNO, 1, 3) || '-' || SUBSTR(U.TLNO, 4, 4) || '-' || SUBSTR(U.TLNO, 8, 4) AS 전화번호
FROM (
    SELECT WRITER_ID
    FROM USED_GOODS_BOARD B
    GROUP BY WRITER_ID
    HAVING COUNT(*) >= 3
) B, USED_GOODS_USER U
WHERE B.WRITER_ID = U.USER_ID
ORDER BY U.USER_ID DESC