-- 코드를 입력하세요
SELECT
    EXTRACT(YEAR FROM S.SALES_DATE) AS YEAR
    ,EXTRACT(MONTH FROM S.SALES_DATE) AS MONTH
    ,U.GENDER
    ,COUNT(DISTINCT U.USER_ID) AS USERS
FROM USER_INFO U, ONLINE_SALE S
WHERE U.USER_ID = S.USER_ID
AND U.GENDER IS NOT NULL
GROUP BY EXTRACT(YEAR FROM S.SALES_DATE), EXTRACT(MONTH FROM S.SALES_DATE), U.GENDER
ORDER BY EXTRACT(YEAR FROM S.SALES_DATE), EXTRACT(MONTH FROM S.SALES_DATE), U.GENDER