-- 코드를 입력하세요

WITH JOINED_2021 AS (
    SELECT USER_ID
    FROM USER_INFO
    WHERE JOINED >= DATE '2021-01-01' AND JOINED <= DATE '2021-12-31'
)

SELECT EXTRACT(YEAR FROM SALES_DATE) AS YEAR, 
EXTRACT(MONTH FROM SALES_DATE) AS MONTH, 
COUNT(DISTINCT USER_ID) AS PURCHASED_USERS, 
ROUND(COUNT(DISTINCT USER_ID) / (SELECT COUNT(*) FROM JOINED_2021), 1) AS PUCHASED_RATIO
FROM ONLINE_SALE
WHERE USER_ID IN (SELECT USER_ID FROM JOINED_2021)
GROUP BY EXTRACT(YEAR FROM SALES_DATE), EXTRACT(MONTH FROM SALES_DATE)
ORDER BY YEAR, MONTH