-- 코드를 입력하세요
SELECT FP.PRODUCT_ID, FP.PRODUCT_NAME, FP.PRICE * FO.SUM_AMOUNT AS TOTAL_SALES
FROM FOOD_PRODUCT FP
, (
    SELECT PRODUCT_ID, SUM(AMOUNT) AS SUM_AMOUNT
    FROM FOOD_ORDER
    WHERE TO_DATE('2022-05-01', 'YYYY-MM-DD') <= PRODUCE_DATE  AND PRODUCE_DATE <= TO_DATE('2022-05-31', 'YYYY-MM-DD')
    GROUP BY PRODUCT_ID
  ) FO
WHERE FP.PRODUCT_ID = FO.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, FP.PRODUCT_ID ASC;
