-- -- 코드를 입력하세요
SELECT HISTORY_ID, 
(1-NVL(DISCOUNT_RATE, 0)/100) * DURATION * DAILY_FEE AS FEE
FROM (
    SELECT C.CAR_ID AS CAR_ID
    ,H.HISTORY_ID AS HISTORY_ID
    ,END_DATE - START_DATE + 1 AS DURATION
    ,C.DAILY_FEE AS DAILY_FEE
    ,(CASE 
        WHEN 7 <= (END_DATE - START_DATE + 1) AND (END_DATE - START_DATE + 1) < 30 THEN '7일 이상'
        WHEN 30 <= (END_DATE - START_DATE + 1) AND (END_DATE - START_DATE + 1) < 90 THEN '30일 이상'
        WHEN 90 <= (END_DATE - START_DATE + 1) THEN '90일 이상'
    END) AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_CAR C, CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    WHERE C.CAR_ID = H.CAR_ID
    AND C.CAR_TYPE = '트럭'
) C, CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
WHERE C.DURATION_TYPE = P.DURATION_TYPE(+)
AND P.CAR_TYPE(+) = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC
