SELECT J.FLAVOR  
FROM  
  (  
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER 
    FROM JULY  
    GROUP BY FLAVOR  
  ) J,  
  (  
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM FIRST_HALF  
    GROUP BY FLAVOR  
  ) FH  
WHERE FH.FLAVOR(+) = J.FLAVOR   
ORDER BY J.TOTAL_ORDER + NVL(FH.TOTAL_ORDER, 0) DESC
FETCH FIRST 3 ROWS ONLY
