-- -- 코드를 입력하세요
-- SELECT MP.MEMBER_NAME, RR.REVIEW_TEXT, RR.REVIEW_DATE
-- FROM MEMBER_PROFILE MP
-- , REST_REVIEW RR
-- WHERE MP.MEMBER_ID = RR.MEMBER_ID
-- AND MP.MEMBER_ID = 
-- (
--     -- 가장 리뷰를 많이 쓴 사람의 id
--     SELECT MEMBER_ID
--     FROM 
--     (
--         SELECT MEMBER_ID, COUNT(*) AS COUNT
--         FROM REST_REVIEW
--         GROUP BY MEMBER_ID
--         ORDER BY COUNT DESC
--     )
--     WHERE ROWNUM = 1
-- )
-- ORDER BY RR.REVIEW_DATE ASC, RR.REVIEW_TEXT ASC;

WITH REVIEW_COUNT (MEMBER_ID, COUNT) AS (
        SELECT MEMBER_ID, COUNT(*)
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
)

SELECT MP.MEMBER_NAME, RR.REVIEW_TEXT, TO_CHAR(RR.REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE
FROM MEMBER_PROFILE MP
, REST_REVIEW RR
, REVIEW_COUNT RC
WHERE 1=1
AND MP.MEMBER_ID = RR.MEMBER_ID
AND RR.MEMBER_ID = RC.MEMBER_ID
AND RC.COUNT = (
    SELECT MAX(COUNT)
    FROM REVIEW_COUNT
)
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC
