-- 코드를 입력하세요
SELECT II.INGREDIENT_TYPE AS INGREDIENT_TYPE, SUM(FF.TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF FF, ICECREAM_INFO II
WHERE FF.FLAVOR = II.FLAVOR
GROUP BY II.INGREDIENT_TYPE
ORDER BY SUM(FF.TOTAL_ORDER) ASC