-- 코드를 작성해주세요
SELECT HE.DEPT_ID, HD.DEPT_NAME_EN, ROUND(HE.AVG_SAL, 0) AS AVG_SAL
FROM (
    SELECT DEPT_ID, AVG(SAL) AS AVG_SAL
    FROM HR_EMPLOYEES
    GROUP BY DEPT_ID
) HE
JOIN HR_DEPARTMENT HD
ON HE.DEPT_ID = HD.DEPT_ID
ORDER BY HE.AVG_SAL DESC;