-- 코드를 작성해주세요
WITH FRONT_CODE AS (
    SELECT SUM(CODE) AS CODE
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
),
PYTHON_CODE AS (
    SELECT CODE FROM SKILLCODES WHERE NAME = 'Python'
),
CSHARP_CODE AS (
    SELECT CODE FROM SKILLCODES WHERE NAME = 'C#'
)
SELECT 
    CASE 
        WHEN SKILL_CODE & (SELECT CODE FROM PYTHON_CODE) AND SKILL_CODE & (SELECT CODE FROM FRONT_CODE) THEN 'A'
        WHEN SKILL_CODE & (SELECT CODE FROM CSHARP_CODE) THEN 'B'
        WHEN SKILL_CODE & (SELECT CODE FROM FRONT_CODE) THEN 'C'
     END AS GRADE
    ,ID
    ,EMAIL
FROM DEVELOPERS
HAVING GRADE IS NOT NULL
ORDER BY GRADE, ID
